### ISSUE TITLE
REQUEST

### ISSUE THREAD

**Issue by agungsugiarto** [codeigniter4projects/playground#2]
Hello, I want to ask a basic tutorial crud with ajax, how to best practice apply it. thank you

**Comment by MGatner** [comment]
I think this would make a great addition! I have some code for it already, I’ll add when I get a chance.

**Comment by agungsugiarto** [comment]
Thank you can't wait. :smiley:

**Comment by agungsugiarto** [comment]
look my repo https://github.com/agungsugiarto/codeigniter4-ajax-crud.git
