### ISSUE TITLE
CI 4.3.2. Development mode doesn't work

### ISSUE THREAD

**Issue by wb027** [codeigniter4projects/playground#202]
CI is installed manually.
Only paths in configs were edited (non-standard paths to 'system' and 'app').

Tried setting developer mode with `.env`:
```
CI_ENVIRONMENT = development
app.baseURL = 'http://wrcc.vags.home'
```
Does not work:
```
$ php spark env

CodeIgniter v4.3.2 Command Line Tool - Server Time: 2023-03-25 17:09:59 UTC+00:00

Your environment is currently set as production.
```

I'm trying to set a constant at the beginning of the index.php:
`
define('CI_ENVIRONMENT', 'development');
`
No effect.

I tried to substitute the `development.php` file instead of `production.php` in the directory `app/Config/Boot/`
No effect.

Environment: Linux Mint 21.1 (Ubuntu 22.04 based), nginx 1.18.0, PHP 7.4.33.

**Comment by MGatner** [comment]
Using .env definitely should work. Have you tried it on a clean install without changing the path variables?

**Comment by kenjis** [comment]
This is Playground repository.
It seems your issue is not specific to this repository.
If you have questions about CI4, please go to the forum.
http://forum.codeigniter.com/forumdisplay.php?fid=30
