### ISSUE TITLE
Issue: .env CI_ENVIRONMENT = development does not show toolbar

### ISSUE THREAD

**Issue by zigmoo** [codeigniter4projects/playground#6]
Hello CI4 Playground Team,

My issue is that changing the 
CI_ENVIRONMENT = production
...to
CI_ENVIRONMENT = development
within the .env file and the site does not show toolbar.

Thanks for your efforts!

Jason

PS: I installed via composer on my webserver, and am using the path "/var/www/ci4playground.cosolis.com" on my server at http://ci4playground.cosolis.com.

**Comment by MGatner** [comment]
What web server and version? Anything in `writable/logs/`? Did you change any config files, or is this “as is”?

We should definitely be supplying development environment by default - I’ll check on that.

**Comment by MichalPB1** [comment]
Please check did you have a correct `app.baseURL` path in `.env` file. I had the same problem last time.

**Comment by zigmoo** [comment]
My only changes are to the .env file:
`app.baseURL = 'http://ci4playground.cosolis.com'`
and
`CI_ENVIRONMENT = development`
no changes in the app/config dir.

My webserver is apache 2.4.29 (Ubuntu);
There are some logs written in writable/logs/
and in the writable/debugbar/ dir, even for today.

Thanks for your responses!  :-)

**Comment by zigmoo** [comment]
Any ideas why the debugbar isn't showing up?

There is a file being generated at ./writable/debugbar/debugbar_1575828758.json:

`{"url":"http:\/\/ci4playground.cosolis.com\/","method":"GET","isAJAX":false,"startTime":1575828758.233235,"totalTime":1.7,"totalMemory":"0.798","segmentDuration":5,"segmentCount":1,"CI_VERSION":"4.0.0-rc.3","collectors":[{"title":"Timers","titleSafe":"timers","titleDetails":"","display":[],"badgeValue":null,"isEmpty":false,"hasTabContent":false,"hasLabel":false,"icon":"","hasTimelineData":true,"timelineData":[{"name":"Bootstrap","component":"Timer","start":1575828758.233272,"duration":0.0013308525085449219},{"name":"Routing","component":"Timer","start":1575828758.234604,"duration":0.00014901161193847656},{"name":"Controller","component":"Timer","start":1575828758.23483,"duration":0.0001270771026611328},{"name":"Controller Constructor","component":"Timer","start":1575828758.234831,"duration":5.888938903808594e-5}]},{"title":"Database","titleSafe":"database","titleDetails":"(0 Queries across 0 Connection)","display":{"queries":[]},"badgeValue":0,"isEmpty":true,"hasTabContent":true,"hasLabel":false,"icon":"data:image\/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAADMSURBVEhLY6A3YExLSwsA4nIycQDIDIhRWEBqamo\/UNF\/SjDQjF6ocZgAKPkRiFeEhoYyQ4WIBiA9QAuWAPEHqBAmgLqgHcolGQD1V4DMgHIxwbCxYD+QBqcKINseKo6eWrBioPrtQBq\/BcgY5ht0cUIYbBg2AJKkRxCNWkDQgtFUNJwtABr+F6igE8olGQD114HMgHIxAVDyAhA\/AlpSA8RYUwoeXAPVex5qHCbIyMgwBCkAuQJIY00huDBUz\/mUlBQDqHGjgBjAwAAACexpph6oHSQAAAAASUVORK5CYII=","hasTimelineData":true,"timelineData":[]},{"title":"Logs","titleSafe":"logs","titleDetails":"","display":{"logs":[]},"badgeValue":null,"isEmpty":true,"hasTabContent":true,"hasLabel":false,"icon":"data:image\/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACYSURBVEhLYxgFJIHU1FSjtLS0i0D8AYj7gEKMEBkqAaAFF4D4ERCvAFrwH4gDoFIMKSkpFkB+OTEYqgUTACXfA\/GqjIwMQyD9H2hRHlQKJFcBEiMGQ7VgAqCBvUgK32dmZspCpagGGNPT0\/1BLqeF4bQHQJePpiIwhmrBBEADR1MRfgB0+WgqAmOoFkwANHA0FY0CUgEDAwCQ0PUpNB3kqwAAAABJRU5ErkJggg==","hasTimelineData":false,"timelineData":[]},{"title":"Views","titleSafe":"views","titleDetails":"","display":[],"badgeValue":1,"isEmpty":false,"hasTabContent":false,"hasLabel":true,"icon":"data:image\/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAADeSURBVEhL7ZSxDcIwEEWNYA0YgGmgyAaJLTcUaaBzQQEVjMEabBQxAdw53zTHiThEovGTfnE\/9rsoRUxhKLOmaa6Uh7X2+UvguLCzVxN1XW9x4EYHzik033Hp3X0LO+DaQG8MDQcuq6qao4qkHuMgQggLvkPLjqh00ZgFDBacMJYFkuwFlH1mshdkZ5JPJERA9JpI6xNCBESvibQ+IURA9JpI6xNCBESvibQ+IURA9DTsuHTOrVFFxixgB\/eUFlU8uKJ0eDBFOu\/9EvoeKnlJS2\/08Tc8NOwQ8sIfMeYFjqKDjdU2sp4AAAAASUVORK5CYII=","hasTimelineData":true,"timelineData":[{"name":"View: welcome_message.php","component":"Views","start":1575828758.234905,"duration":3.0994415283203125e-5}]},{"title":"Files","titleSafe":"files","titleDetails":"( 85 )","display":{"coreFiles":[{"name":"AutoloadConfig.php","path":"SYSTEMPATH\/Config\/AutoloadConfig.php"},{"name":"Autoloader.php","path":"SYSTEMPATH\/Autoloader\/Autoloader.php"},{"name":"BaseCollector.php","path":"SYSTEMPATH\/Debug\/Toolbar\/Collectors\/BaseCollector.php"},{"name":"BaseConfig.php","path":"SYSTEMPATH\/Config\/BaseConfig.php"},{"name":"BaseService.php","path":"SYSTEMPATH\/Config\/BaseService.php"},{"name":"CacheFactory.php","path":"SYSTEMPATH\/Cache\/CacheFactory.php"},{"name":"CacheInterface.php","path":"SYSTEMPATH\/Cache\/CacheInterface.php"},{"name":"CodeIgniter.php","path":"SYSTEMPATH\/CodeIgniter.php"},{"name":"Common.php","path":"SYSTEMPATH\/Common.php"},{"name":"Config.php","path":"SYSTEMPATH\/Config\/Config.php"},{"name":"Config.php","path":"SYSTEMPATH\/Database\/Config.php"},{"name":"Controller.php","path":"SYSTEMPATH\/Controller.php"},{"name":"Database.php","path":"SYSTEMPATH\/Debug\/Toolbar\/Collectors\/Database.php"},{"name":"DebugToolbar.php","path":"SYSTEMPATH\/Filters\/DebugToolbar.php"},{"name":"DotEnv.php","path":"SYSTEMPATH\/Config\/DotEnv.php"},{"name":"Events.php","path":"SYSTEMPATH\/Debug\/Toolbar\/Collectors\/Events.php"},{"name":"Events.php","path":"SYSTEMPATH\/Events\/Events.php"},{"name":"Exceptions.php","path":"SYSTEMPATH\/Debug\/Exceptions.php"},{"name":"FileHandler.php","path":"SYSTEMPATH\/Cache\/Handlers\/FileHandler.php"},{"name":"FileLocator.php","path":"SYSTEMPATH\/Autoloader\/FileLocator.php"},{"name":"Files.php","path":"SYSTEMPATH\/Debug\/Toolbar\/Collectors\/Files.php"},{"name":"FilterInterface.php","path":"SYSTEMPATH\/Filters\/FilterInterface.php"},{"name":"Filters.php","path":"SYSTEMPATH\/Filters\/Filters.php"},{"name":"Header.php","path":"SYSTEMPATH\/HTTP\/Header.php"},{"name":"IncomingRequest.php","path":"SYSTEMPATH\/HTTP\/IncomingRequest.php"},{"name":"Logger.php","path":"SYSTEMPATH\/Log\/Logger.php"},{"name":"LoggerInterface.php","path":"SYSTEMPATH\/ThirdParty\/PSR\/Log\/LoggerInterface.php"},{"name":"Logs.php","path":"SYSTEMPATH\/Debug\/Toolbar\/Collectors\/Logs.php"},{"name":"Message.php","path":"SYSTEMPATH\/HTTP\/Message.php"},{"name":"RendererInterface.php","path":"SYSTEMPATH\/View\/RendererInterface.php"},{"name":"Request.php","path":"SYSTEMPATH\/HTTP\/Request.php"},{"name":"RequestInterface.php","path":"SYSTEMPATH\/HTTP\/RequestInterface.php"},{"name":"Response.php","path":"SYSTEMPATH\/HTTP\/Response.php"},{"name":"ResponseInterface.php","path":"SYSTEMPATH\/HTTP\/ResponseInterface.php"},{"name":"ResponseTrait.php","path":"SYSTEMPATH\/API\/ResponseTrait.php"},{"name":"RouteCollection.php","path":"SYSTEMPATH\/Router\/RouteCollection.php"},{"name":"RouteCollectionInterface.php","path":"SYSTEMPATH\/Router\/RouteCollectionInterface.php"},{"name":"Router.php","path":"SYSTEMPATH\/Router\/Router.php"},{"name":"RouterInterface.php","path":"SYSTEMPATH\/Router\/RouterInterface.php"},{"name":"Routes.php","path":"SYSTEMPATH\/Config\/Routes.php"},{"name":"Routes.php","path":"SYSTEMPATH\/Debug\/Toolbar\/Collectors\/Routes.php"},{"name":"Services.php","path":"SYSTEMPATH\/Config\/Services.php"},{"name":"Timer.php","path":"SYSTEMPATH\/Debug\/Timer.php"},{"name":"Timers.php","path":"SYSTEMPATH\/Debug\/Toolbar\/Collectors\/Timers.php"},{"name":"Toolbar.php","path":"SYSTEMPATH\/Debug\/Toolbar.php"},{"name":"URI.php","path":"SYSTEMPATH\/HTTP\/URI.php"},{"name":"UserAgent.php","path":"SYSTEMPATH\/HTTP\/UserAgent.php"},{"name":"View.php","path":"SYSTEMPATH\/Config\/View.php"},{"name":"View.php","path":"SYSTEMPATH\/View\/View.php"},{"name":"Views.php","path":"SYSTEMPATH\/Debug\/Toolbar\/Collectors\/Views.php"},{"name":"bootstrap.php","path":"SYSTEMPATH\/bootstrap.php"},{"name":"kint.php","path":"SYSTEMPATH\/ThirdParty\/Kint\/kint.php"},{"name":"url_helper.php","path":"SYSTEMPATH\/Helpers\/url_helper.php"}],"userFiles":[{"name":"App.php","path":"APPPATH\/Config\/App.php"},{"name":"Autoload.php","path":"APPPATH\/Config\/Autoload.php"},{"name":"BaseController.php","path":"APPPATH\/Controllers\/BaseController.php"},{"name":"Cache.php","path":"APPPATH\/Config\/Cache.php"},{"name":"ClassLoader.php","path":"\/var\/www\/c4playground.cosolis.com\/vendor\/composer\/ClassLoader.php"},{"name":"Constants.php","path":"APPPATH\/Config\/Constants.php"},{"name":"Database.php","path":"APPPATH\/Config\/Database.php"},{"name":"Events.php","path":"APPPATH\/Config\/Events.php"},{"name":"Exceptions.php","path":"APPPATH\/Config\/Exceptions.php"},{"name":"Filters.php","path":"APPPATH\/Config\/Filters.php"},{"name":"Home.php","path":"APPPATH\/Controllers\/Home.php"},{"name":"Kint.php","path":"\/var\/www\/c4playground.cosolis.com\/vendor\/kint-php\/kint\/src\/Kint.php"},{"name":"Logger.php","path":"APPPATH\/Config\/Logger.php"},{"name":"Modules.php","path":"APPPATH\/Config\/Modules.php"},{"name":"Paths.php","path":"APPPATH\/Config\/Paths.php"},{"name":"Routes.php","path":"APPPATH\/Config\/Routes.php"},{"name":"Services.php","path":"APPPATH\/Config\/Services.php"},{"name":"Toolbar.php","path":"APPPATH\/Config\/Toolbar.php"},{"name":"UserAgents.php","path":"APPPATH\/Config\/UserAgents.php"},{"name":"View.php","path":"APPPATH\/Config\/View.php"},{"name":"autoload.php","path":"\/var\/www\/c4playground.cosolis.com\/vendor\/autoload.php"},{"name":"autoload_real.php","path":"\/var\/www\/c4playground.cosolis.com\/vendor\/composer\/autoload_real.php"},{"name":"autoload_static.php","path":"\/var\/www\/c4playground.cosolis.com\/vendor\/composer\/autoload_static.php"},{"name":"bootstrap.php","path":"\/var\/www\/c4playground.cosolis.com\/vendor\/symfony\/polyfill-ctype\/bootstrap.php"},{"name":"deep_copy.php","path":"\/var\/www\/c4playground.cosolis.com\/vendor\/myclabs\/deep-copy\/src\/DeepCopy\/deep_copy.php"},{"name":"development.php","path":"APPPATH\/Config\/Boot\/development.php"},{"name":"index.php","path":"FCPATH\/index.php"},{"name":"init.php","path":"\/var\/www\/c4playground.cosolis.com\/vendor\/kint-php\/kint\/init.php"},{"name":"init_footer.php","path":"\/var\/www\/c4playground.cosolis.com\/vendor\/kint-php\/kint\/init_footer.php"},{"name":"init_header.php","path":"\/var\/www\/c4playground.cosolis.com\/vendor\/kint-php\/kint\/init_header.php"},{"name":"init_helpers.php","path":"\/var\/www\/c4playground.cosolis.com\/vendor\/kint-php\/kint\/init_helpers.php"},{"name":"welcome_message.php","path":"APPPATH\/Views\/welcome_message.php"}]},"badgeValue":85,"isEmpty":false,"hasTabContent":true,"hasLabel":false,"icon":"data:image\/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAGBSURBVEhL7ZQ9S8NQGIVTBQUncfMfCO4uLgoKbuKQOWg+OkXERRE1IAXrIHbVDrqIDuLiJgj+gro7S3dnpfq88b1FMTE3VZx64HBzzvvZWxKnj15QCcPwCD5HUfSWR+JtzgmtsUcQBEva5IIm9SwSu+95CAWbUuy67qBa32ByZEDpIaZYZSZMjjQuPcQUq8yEyYEb8FSerYeQVGbAFzJkX1PyQWLhgCz0BxTCekC1Wp0hsa6yokzhed4oje6Iz6rlJEkyIKfUEFtITVtQdAibn5rMyaYsMS+a5wTv8qeXMhcU16QZbKgl3hbs+L4\/pnpdc87MElZgq10p5DxGdq8I7xrvUWUKvG3NbSK7ubngYzdJwSsF7TiOh9VOgfcEz1UayNe3JUPM1RWC5GXYgTfc75B4NBmXJnAtTfpABX0iPvEd9ezALwkplCFXcr9styiNOKc1RRZpaPM9tcqBwlWzGY1qPL9wjqRBgF5BH6j8HWh2S7MHlX8PrmbK+k\/8PzjOOzx1D3i1pKTTAAAAAElFTkSuQmCC","hasTimelineData":false,"timelineData":[]},{"title":"Routes","titleSafe":"routes","titleDetails":"","display":{"matchedRoute":[{"directory":"","controller":"\\App\\Controllers\\Home","method":"index","paramCount":0,"truePCount":0,"params":[]}],"routes":[{"from":"\/","to":"\\App\\Controllers\\Home::index"},{"from":"basecontroller(.*)","to":{}},{"from":"(.*)\/initController","to":{}}]},"badgeValue":3,"isEmpty":false,"hasTabContent":true,"hasLabel":false,"icon":"data:image\/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAFDSURBVEhL7ZRNSsNQFIUjVXSiOFEcuQIHDpzpxC0IGYeE\/BEInbWlCHEDLsSiuANdhKDjgm6ggtSJ+l25ldrmmTwIgtgDh\/t37r1J+16cX0dRFMtpmu5pWAkrvYjjOB7AETzStBFW+inxu3KUJMmhludQpoflS1zXban4LYqiO224h6VLTHr8Z+z8EpIHFF9gG78nDVmW7UgTHKjsCyY98QP+pcq+g8Ku2s8G8X3f3\/I8b038WZTp+bO38zxfFd+I6YY6sNUvFlSDk9CRhiAI1jX1I9Cfw7GG1UB8LAuwbU0ZwQnbRDeEN5qqBxZMLtE1ti9LtbREnMIuOXnyIf5rGIb7Wq8HmlZgwYBH7ORTcKH5E4mpjeGt9fBZcHE2GCQ3Vt7oTNPNg+FXLHnSsHkw\/FR+Gg2bB8Ptzrst\/v6C\/wrH+QB+duli6MYJdQAAAABJRU5ErkJggg==","hasTimelineData":false,"timelineData":[]},{"title":"Events","titleSafe":"events","titleDetails":"","display":{"events":{"pre_system":{"event":"pre_system","duration":"0.83","count":1}}},"badgeValue":1,"isEmpty":false,"hasTabContent":true,"hasLabel":false,"icon":"data:image\/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAEASURBVEhL7ZXNDcIwDIVTsRBH1uDQDdquUA6IM1xgCA6MwJUN2hk6AQzAz0vl0ETUxC5VT3zSU5w81\/mRMGZysixbFEVR0jSKNt8geQU9aRpFmp\/keX6AbjZ5oB74vsaN5lSzA4tLSjpBFxsjeSuRy4d2mDdQTWU7YLbXTNN05mKyovj5KL6B7q3hoy3KwdZxBlT+Ipz+jPHrBqOIynZgcZonoukb\/0ckiTHqNvDXtXEAaygRbaB9FvUTjRUHsIYS0QaSp+Dw6wT4hiTmYHOcYZsdLQ2CbXa4ftuuYR4x9vYZgdb4vsFYUdmABMYeukK9\/SUme3KMFQ77+Yfzh8eYF8+orDuDWU5LAAAAAElFTkSuQmCC","hasTimelineData":false,"timelineData":[]}],"vars":{"varData":{"View Data":[]},"headers":{"Host":"c4playground.cosolis.com","Upgrade-Insecure-Requests":"1","Accept":"text\/html,application\/xhtml+xml,application\/xml;q=0.9,*\/*;q=0.8","User-Agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit\/605.1.15 (KHTML, like Gecko) Version\/13.0.3 Safari\/605.1.15","Accept-Language":"en-us","Accept-Encoding":"gzip, deflate","Connection":"keep-alive"},"request":"HTTP\/1.1","response":{"statusCode":200,"reason":"OK","contentType":"text\/html; charset=UTF-8"}},"config":{"ciVersion":"4.0.0-rc.3","phpVersion":"7.2.22-1+ubuntu18.04.1+deb.sury.org+1","phpSAPI":"apache2handler","environment":"development","baseURL":"http:\/\/ci4playground.cosolis.com","timezone":"America\/Chicago","locale":"en","cspEnabled":false}}% `

**Comment by MichalPB1** [comment]
Please open your browser console and check in `Network` tab request for `debugbar' and give details. Do you have `200` status?

**Comment by lonnieezell** [comment]
The most common thing I see here is that the `baseURL` as set in `app\Config\App.php` doesn't match exactly to what you're serving it from. For me, it's often that I've used a different port than what is in the file.

**Comment by zigmoo** [comment]
Yes, you were right Lonnie, thanks.
And Thanks to MichalPB1 for the good advice of checking the network tab in browser dev tools.

I've now ironed out an issue where my baseURL was off by a letter. Fixed one is http://ci4playground.cosolis.com.
I've made no changes to the app/Config/*, but only to these two lines of the .env:
```
CI_ENVIRONMENT = development
app.baseURL = 'http://ci4playground.cosolis.com'
```

Now, I still don't get the debug toolbar, but thankfully this time I get an error 500 coming back in reply to the Home page requesting the toolbar.

This is what my /writable/logs/<today's log.php> says.
Any ideas?

`CRITICAL - 2019-12-10 23:05:24 --> Undefined property: Config\App::$CSRFHeaderName
#0 /var/www/ci4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/Security/Security.php(184): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', '/var/www/ci4pla...', 184, Array)
#1 /var/www/ci4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/Config/Services.php(737): CodeIgniter\Security\Security->__construct(Object(Config\App))
#2 /var/www/ci4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/Config/BaseService.php(120): CodeIgniter\Config\Services::security(Object(Config\App), false)
#3 /var/www/ci4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/Config/Services.php(729): CodeIgniter\Config\BaseService::getSharedInstance('security', NULL)
#4 /var/www/ci4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/Helpers/security_helper.php(59): CodeIgniter\Config\Services::security()
#5 /var/www/ci4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/Debug/Toolbar.php(448): sanitize_filename('debugbar_157604...')
#6 /var/www/ci4playground.cosolis.com/app/Config/Events.php(41): CodeIgniter\Debug\Toolbar->respond()
#7 [internal function]: CodeIgniter\Events\Events::Config\{closure}()
#8 /var/www/ci4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/Events/Events.php(188): call_user_func(Object(Closure))
#9 /var/www/ci4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/CodeIgniter.php(227): CodeIgniter\Events\Events::trigger('pre_system')
#10 /var/www/ci4playground.cosolis.com/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
`

**Comment by zigmoo** [comment]
Here's the Response from the Error 500 to index.php's XHR: 
`{
    "title": "ErrorException",
    "type": "ErrorException",
    "code": 500,
    "message": "Undefined property: Config\\App::$CSRFHeaderName",
    "file": "/var/www/ci4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/Security/Security.php",
    "line": 184,
    "trace": [
        {
            "file": "/var/www/ci4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/Security/Security.php",
            "line": 184,
            "function": "errorHandler",
            "class": "CodeIgniter\\Debug\\Exceptions",
            "type": "->",
            "args": [
                8,
                "Undefined property: Config\\App::$CSRFHeaderName",
                "/var/www/ci4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/Security/Security.php",
                184,
                {
                    "config": {
                        "baseURL": "http://ci4playground.cosolis.com",
                        "indexPage": "index.php",
                        "uriProtocol": "REQUEST_URI",
                        "defaultLocale": "en",
                        "negotiateLocale": false,
                        "supportedLocales": [
                            "en"
                        ],
                        "appTimezone": "America/Chicago",
                        "charset": "UTF-8",
                        "forceGlobalSecureRequests": false,
                        "sessionDriver": "CodeIgniter\\Session\\Handlers\\FileHandler",
                        "sessionCookieName": "ci_session",
                        "sessionExpiration": 7200,
                        "sessionSavePath": "/var/www/ci4playground.cosolis.com/writable/session",
                        "sessionMatchIP": false,
                        "sessionTimeToUpdate": 300,
                        "sessionRegenerateDestroy": false,
                        "cookiePrefix": "",
                        "cookieDomain": "",
                        "cookiePath": "/",
                        "cookieSecure": false,
                        "cookieHTTPOnly": false,
                        "proxyIPs": "",
                        "CSRFTokenName": "csrf_test_name",
                        "CSRFCookieName": "csrf_cookie_name",
                        "CSRFExpire": 7200,
                        "CSRFRegenerate": true,
                        "CSRFRedirect": true,
                        "CSPEnabled": false
                    }
                }
            ]
        },
        {
            "file": "/var/www/ci4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/Config/Services.php",
            "line": 737,
            "function": "__construct",
            "class": "CodeIgniter\\Security\\Security",
            "type": "->",
            "args": [
                {
                    "baseURL": "http://ci4playground.cosolis.com",
                    "indexPage": "index.php",
                    "uriProtocol": "REQUEST_URI",
                    "defaultLocale": "en",
                    "negotiateLocale": false,
                    "supportedLocales": [
                        "en"
                    ],
                    "appTimezone": "America/Chicago",
                    "charset": "UTF-8",
                    "forceGlobalSecureRequests": false,
                    "sessionDriver": "CodeIgniter\\Session\\Handlers\\FileHandler",
                    "sessionCookieName": "ci_session",
                    "sessionExpiration": 7200,
                    "sessionSavePath": "/var/www/ci4playground.cosolis.com/writable/session",
                    "sessionMatchIP": false,
                    "sessionTimeToUpdate": 300,
                    "sessionRegenerateDestroy": false,
                    "cookiePrefix": "",
                    "cookieDomain": "",
                    "cookiePath": "/",
                    "cookieSecure": false,
                    "cookieHTTPOnly": false,
                    "proxyIPs": "",
                    "CSRFTokenName": "csrf_test_name",
                    "CSRFCookieName": "csrf_cookie_name",
                    "CSRFExpire": 7200,
                    "CSRFRegenerate": true,
                    "CSRFRedirect": true,
                    "CSPEnabled": false
                }
            ]
        },
        {
            "file": "/var/www/ci4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/Config/BaseService.php",
            "line": 120,
            "function": "security",
            "class": "CodeIgniter\\Config\\Services",
            "type": "::",
            "args": [
                {
                    "baseURL": "http://ci4playground.cosolis.com",
                    "indexPage": "index.php",
                    "uriProtocol": "REQUEST_URI",
                    "defaultLocale": "en",
                    "negotiateLocale": false,
                    "supportedLocales": [
                        "en"
                    ],
                    "appTimezone": "America/Chicago",
                    "charset": "UTF-8",
                    "forceGlobalSecureRequests": false,
                    "sessionDriver": "CodeIgniter\\Session\\Handlers\\FileHandler",
                    "sessionCookieName": "ci_session",
                    "sessionExpiration": 7200,
                    "sessionSavePath": "/var/www/ci4playground.cosolis.com/writable/session",
                    "sessionMatchIP": false,
                    "sessionTimeToUpdate": 300,
                    "sessionRegenerateDestroy": false,
                    "cookiePrefix": "",
                    "cookieDomain": "",
                    "cookiePath": "/",
                    "cookieSecure": false,
                    "cookieHTTPOnly": false,
                    "proxyIPs": "",
                    "CSRFTokenName": "csrf_test_name",
                    "CSRFCookieName": "csrf_cookie_name",
                    "CSRFExpire": 7200,
                    "CSRFRegenerate": true,
                    "CSRFRedirect": true,
                    "CSPEnabled": false
                },
                false
            ]
        },
        {
            "file": "/var/www/ci4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/Config/Services.php",
            "line": 729,
            "function": "getSharedInstance",
            "class": "CodeIgniter\\Config\\BaseService",
            "type": "::",
            "args": [
                "security",
                null
            ]
        },
        {
            "file": "/var/www/ci4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/Helpers/security_helper.php",
            "line": 59,
            "function": "security",
            "class": "CodeIgniter\\Config\\Services",
            "type": "::",
            "args": []
        },
        {
            "file": "/var/www/ci4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/Debug/Toolbar.php",
            "line": 448,
            "function": "sanitize_filename",
            "args": [
                "debugbar_1576041542"
            ]
        },
        {
            "file": "/var/www/ci4playground.cosolis.com/app/Config/Events.php",
            "line": 41,
            "function": "respond",
            "class": "CodeIgniter\\Debug\\Toolbar",
            "type": "->",
            "args": []
        },
        {
            "function": "Config\\{closure}",
            "class": "CodeIgniter\\Events\\Events",
            "type": "::",
            "args": []
        },
        {
            "file": "/var/www/ci4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/Events/Events.php",
            "line": 188,
            "function": "call_user_func",
            "args": [
                {}
            ]
        },
        {
            "file": "/var/www/ci4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/CodeIgniter.php",
            "line": 227,
            "function": "trigger",
            "class": "CodeIgniter\\Events\\Events",
            "type": "::",
            "args": [
                "pre_system"
            ]
        },
        {
            "file": "/var/www/ci4playground.cosolis.com/public/index.php",
            "line": 45,
            "function": "run",
            "class": "CodeIgniter\\CodeIgniter",
            "type": "->",
            "args": []
        }
    ]
}`

**Comment by MichalPB1** [comment]
Please update a CI4 app directory files. Recently was add a new params to App/Config file which are missing in your code. Please compare your app config files with files from CI4 app repository or overwrite app directory if you dont have there any changes.

**Comment by MGatner** [comment]
MichalPB1 is correct, and that should be an easy fix. This was changed in the Playground repo as well (https://github.com/codeigniter4projects/playground/commit/c418e959e8be4cc6095a780d0965dd0a21b48739) so if you are using an unmodified version you can just pull the latest repo to fix the problem.

**Comment by MGatner** [comment]
@zigmoo Is this still an active issue for you?
