### ISSUE TITLE
Failure: php spark migrate php spark db:seed PlaygroundSeeder

### ISSUE THREAD

**Issue by zigmoo** [codeigniter4projects/playground#7]
Hello CI4 Playground Team,

I installed the CI4 Playground on one of my servers at http://c4playground.cosolis.com.

After performing a composer update within the site directory, I ran the command
php spark migrate php spark db:seed PlaygroundSeeder
and got the following error:

`╰─± php spark migrate php spark db:seed PlaygroundSeeder

CodeIgniter CLI Tool - Version 4.0.0-rc.3 - Server-Time: 2019-11-26 20:10:54pm

Running all new migrations...
An uncaught Exception was encountered

Type:        Error
Message:     Class 'SQLite3' not found
Filename:    /var/www/c4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/Database/SQLite3/Connection.php
Line Number: 89

	Backtrace:
						-377 - /var/www/c4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/Database/BaseConnection.php::connect
								-643 - /var/www/c4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/Database/BaseConnection.php::initialize
								-1547 - /var/www/c4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/Database/BaseConnection.php::query
								-1590 - /var/www/c4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/Database/BaseConnection.php::listTables
								-939 - /var/www/c4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/Database/MigrationRunner.php::tableExists
								-193 - /var/www/c4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/Database/MigrationRunner.php::ensureTable
								-128 - /var/www/c4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/Commands/Database/Migrate.php::latest
								-137 - /var/www/c4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/CLI/CommandRunner.php::run
								-110 - /var/www/c4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/CLI/CommandRunner.php::runCommand
								-86 - /var/www/c4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/CLI/CommandRunner.php::index
								-843 - /var/www/c4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/CodeIgniter.php::_remap
								-338 - /var/www/c4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/CodeIgniter.php::runController
								-246 - /var/www/c4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/CodeIgniter.php::handleRequest
								-86 - /var/www/c4playground.cosolis.com/vendor/codeigniter4/codeigniter4/system/CLI/Console.php::run
								-56 - /var/www/c4playground.cosolis.com/spark::run
`

**Comment by zigmoo** [comment]
Looks like this is due to my phpcli version (7.3 on Ubuntu 18) lacking the SQlite3 module for some reason... My web-facing php has SQlite3, and so has no such problem.

Executing the following command on my Ubuntu 18 server fixed the issue:
`sudo apt-get install php7.3-sqlite3`

> php spark migrate php spark db:seed PlaygroundSeeder
CodeIgniter CLI Tool - Version 4.0.0-rc.3 - Server-Time: 2019-11-26 22:32:34pm
Running all new migrations...
	Running: (App) 2019-11-21-175417_App\Database\Migrations\CreatePlaygroundTables
Done

**Comment by MGatner** [comment]
Gotcha, glad it was something straightforward! I wonder if we should be checking for that or if the native error is sufficient?
